version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=leadgenie
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=leadgenie_dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - leadgenie-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=leadgenie
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leadgenie_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leadgenie-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - leadgenie-network

volumes:
  postgres_data:
  redis_data:

networks:
  leadgenie-network:
    driver: bridge 